spring.application.name=docflow-service
server.port=8081

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Auth
app.auth.username=admin
app.auth.password=admin123
app.jwt.secret=${JWT_SECRET}
app.jwt.expiry-ms=86400000

# AWS
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.presigned-put-ttl-minutes=${AWS_S3_PUT_TTL_MINUTES:15}
aws.s3.presigned-get-ttl-days=${AWS_S3_GET_TTL_DAYS:7}
